### ISSUE TITLE
关于node和iterator实现的问题

### ISSUE THREAD

**Issue by ycszen** [zouxiaohang/TinySTL#5]
你好，最近对照着看sgi_stl源码和你写的tinySTL源码的时候发现一个问题：(就list而言)
sgi_stl源码在实现list 的时候，他的node，和iterator都分别实现了一个node_base, iterator_base,然后node，iterator分别继承node_base, iterator_base.为什么需要这样实现呢?
我的想法是，node_base, iterator_base都是非泛型编程，然后node，iterator都是在node_base, iterator_base的基础上加入了泛型编程。这样能减少泛型编程编译时产生的冗余代码。不知这个想法是否正确。
如能回复，万分感谢。

**Comment by zouxiaohang** [comment]
额，其实我还没看出这样设计的好处在哪，所以我也没用这样的设计思路

**Comment by ycszen** [comment]
OK,谢谢啦~
那我再查阅一下其他资料，如果有所领悟再告知你。
